In [9]:
import pandas as pd
import numpy as np
import os
import math
from sklearn.metrics import classification_report, confusion_matrix

In [8]:
df = pd.read_csv('test_predictions.csv')
print(classification_report(df['label'],df['predictions']))
print(confusion_matrix(df['label'],df['predictions']))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       250
           1       0.97      0.88      0.92       250
           2       0.99      0.98      0.98       250
           3       0.88      0.99      0.93       250

    accuracy                           0.96      1000
   macro avg       0.96      0.96      0.96      1000
weighted avg       0.96      0.96      0.96      1000

[[244   5   0   1]
 [  0 220   1  29]
 [  0   0 245   5]
 [  0   1   2 247]]


In [10]:
df = pd.read_csv('C:/Users/mkhan/Desktop/musabi/OCT_project/data/oct/OCT_100.csv')

In [3]:
df.head()

image  label
0   NORMAL-1001772-1.jpeg      0
1  NORMAL-1001772-10.jpeg      0
2  NORMAL-1001772-11.jpeg      0
3  NORMAL-1001772-12.jpeg      0
4  NORMAL-1001772-13.jpeg      0

In [11]:
# combining the image and label for training
df2 = df.assign(path='data/oct/OCT_100/'+df['label'].astype(str)+'/'+df['image'].astype(str))

In [34]:
#one_hot = pd.get_dummies(df['Finding Labels'])
#one_hot.head()
#df = pd.concat([df,one_hot],axis=1)

In [4]:
df2.to_csv('C:/Users/mkhan/Desktop/musabi/OCT_project/data/oct/OCT_100_csv.csv')

In [6]:
df=pd.read_csv('C:/Users/mkhan/Desktop/musabi/OCT_project/data/oct/val_csv.csv')

In [7]:
df['source']='oct_mendely'

In [5]:
df.to_csv('C:/Users/mkhan/Desktop/musabi/OCT_project/data/covid_pneu/val_csv.csv')

## Splitting the data into train and test from CSv

In [27]:
df = pd.read_csv('C:/Users/mkhan/Desktop/musabi/OCT_project/data/oct/train.csv')
total_size = len(df)
train_size =math.floor(0.80*total_size)

In [ ]:
#shuffle the data before splitting
from sklearn.utils import shuffle
df =shuffle(df)

In [31]:
#splitting into train and test
train =df.head(train_size)
test = df.tail(len(df) - train_size)
train.to_csv('C:/Users/mkhan/Desktop/musabi/OCT_project/data/covid_pneu/training_csv.csv')
test.to_csv('C:/Users/mkhan/Desktop/musabi/OCT_project/data/covid_pneu/testing_csv.csv')